/****** Object:  Database [CuaHangNoiBo]    Script Date: 22/12/2022 12:19:56 SA ******/
CREATE DATABASE [CuaHangNoiBo]

GO
ALTER DATABASE [CuaHangNoiBo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET ARITHABORT OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CuaHangNoiBo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CuaHangNoiBo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CuaHangNoiBo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CuaHangNoiBo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET RECOVERY FULL 
GO
ALTER DATABASE [CuaHangNoiBo] SET  MULTI_USER 
GO
ALTER DATABASE [CuaHangNoiBo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CuaHangNoiBo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CuaHangNoiBo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CuaHangNoiBo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CuaHangNoiBo] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CuaHangNoiBo] SET QUERY_STORE = OFF
GO
USE [CuaHangNoiBo]
GO
/****** Object:  Table [dbo].[CTPN]    Script Date: 22/12/2022 12:19:56 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTPN](
	[maPN] [int] NOT NULL,
	[maNCC] [int] NOT NULL,
	[maSP] [int] NOT NULL,
	[tenSP] [nvarchar](50) NULL,
	[hangSP] [nvarchar](20) NULL,
	[soLuong] [int] NOT NULL,
	[giaSP] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTHD]    Script Date: 22/12/2022 12:19:56 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTHD](
	[maHD] [int] NOT NULL,
	[maSP] [int] NOT NULL,
	[soLuong] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DangNhap]    Script Date: 22/12/2022 12:19:56 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DangNhap](
	[id] [int] NOT NULL,
	[pass] [nvarchar](20) NOT NULL,
	[dayCreated] [datetime] NULL,
	[isAdmin] [int] NULL,
 CONSTRAINT [PK_DangNhap] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HoaDon]    Script Date: 22/12/2022 12:19:56 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HoaDon](
	[maHD] [int] NOT NULL,
	[maNV] [int] NOT NULL,
	[hoTenKH] [nvarchar](max) NOT NULL,
	[diaChi] [nvarchar](max) NOT NULL,
	[SDT] [nvarchar](max) NOT NULL,
	[dayCreate] [date] NULL,
	[baoHanh] [int] NOT NULL,
 CONSTRAINT [PK_HoaDon] PRIMARY KEY CLUSTERED 
(
	[maHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NhaCungCap]    Script Date: 22/12/2022 12:19:56 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhaCungCap](
	[maNCC] [int] NOT NULL,
	[tenNCC] [nvarchar](50) NOT NULL,
	[diaChi] [nvarchar](max) NOT NULL,
	[dayCreate] [date] NOT NULL,
	[SDT] [varchar](10) NOT NULL,
 CONSTRAINT [PK_NhaCungCap] PRIMARY KEY CLUSTERED 
(
	[maNCC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NhanVien]    Script Date: 22/12/2022 12:19:56 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhanVien](
	[maNV] [int] NOT NULL,
	[hoTen] [nvarchar](50) NOT NULL,
	[cmnd] [varchar](12) NOT NULL,
	[sdt] [varchar](10) NOT NULL,
	[diaChi] [nvarchar](max) NULL,
	[ngaySinh] [date] NULL,
	[soGio] [int] NULL,
	[ImageByte] [varbinary](max) NULL,
 CONSTRAINT [PK_NhanVien] PRIMARY KEY CLUSTERED 
(
	[maNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PhieuNhap]    Script Date: 22/12/2022 12:19:56 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PhieuNhap](
	[maPN] [int] NOT NULL,
	[ngayTao] [datetime] NOT NULL,
	[daDuyet] [int] NOT NULL,
 CONSTRAINT [PK_PhieuNhap] PRIMARY KEY CLUSTERED 
(
	[maPN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SanPham]    Script Date: 22/12/2022 12:19:56 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SanPham](
	[maSP] [int] NOT NULL,
	[maNCC] [int] NULL,
	[tenSP] [nvarchar](50) NOT NULL,
	[soLuong] [int] NOT NULL,
	[hangSP] [nvarchar](30) NOT NULL,
	[hanBaoHanh] [int] NULL,
	[giaSP] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_SanPham] PRIMARY KEY CLUSTERED 
(
	[maSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TinNhan]    Script Date: 22/12/2022 12:19:56 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TinNhan](
	[idNV] [int] NOT NULL,
	[idTN] [int] NOT NULL,
	[tinNhan] [nvarchar](max) NOT NULL,
	[thoiGian] [datetime] NULL,
	[daDuyet] [int] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTPN]  WITH CHECK ADD  CONSTRAINT [FK_CTPN_NhaCungCap] FOREIGN KEY([maNCC])
REFERENCES [dbo].[NhaCungCap] ([maNCC])
GO
ALTER TABLE [dbo].[CTPN] CHECK CONSTRAINT [FK_CTPN_NhaCungCap]
GO
ALTER TABLE [dbo].[CTPN]  WITH CHECK ADD  CONSTRAINT [FK_CTPN_PhieuNhap] FOREIGN KEY([maPN])
REFERENCES [dbo].[PhieuNhap] ([maPN])
GO
ALTER TABLE [dbo].[CTPN] CHECK CONSTRAINT [FK_CTPN_PhieuNhap]
GO
ALTER TABLE [dbo].[CTHD]  WITH CHECK ADD  CONSTRAINT [FK_CTHD_HoaDon] FOREIGN KEY([maHD])
REFERENCES [dbo].[HoaDon] ([maHD])
GO
ALTER TABLE [dbo].[CTHD] CHECK CONSTRAINT [FK_CTHD_HoaDon]
GO
ALTER TABLE [dbo].[CTHD]  WITH CHECK ADD  CONSTRAINT [FK_CTHD_SanPham] FOREIGN KEY([maSP])
REFERENCES [dbo].[SanPham] ([maSP])
GO
ALTER TABLE [dbo].[CTHD] CHECK CONSTRAINT [FK_CTHD_SanPham]
GO
ALTER TABLE [dbo].[HoaDon]  WITH CHECK ADD  CONSTRAINT [FK_HoaDon_NhanVien] FOREIGN KEY([maNV])
REFERENCES [dbo].[NhanVien] ([maNV])
GO
ALTER TABLE [dbo].[HoaDon] CHECK CONSTRAINT [FK_HoaDon_NhanVien]
GO
ALTER TABLE [dbo].[NhaCungCap]  WITH CHECK ADD  CONSTRAINT [FK_NhaCungCap_DangNhap] FOREIGN KEY([maNCC])
REFERENCES [dbo].[DangNhap] ([id])
GO
ALTER TABLE [dbo].[NhaCungCap] CHECK CONSTRAINT [FK_NhaCungCap_DangNhap]
GO
ALTER TABLE [dbo].[NhanVien]  WITH CHECK ADD  CONSTRAINT [FK_NhanVien_DangNhap] FOREIGN KEY([maNV])
REFERENCES [dbo].[DangNhap] ([id])
GO
ALTER TABLE [dbo].[NhanVien] CHECK CONSTRAINT [FK_NhanVien_DangNhap]
GO
ALTER TABLE [dbo].[TinNhan]  WITH CHECK ADD  CONSTRAINT [FK_TinNhan_DangNhap] FOREIGN KEY([idNV])
REFERENCES [dbo].[DangNhap] ([id])
GO
ALTER TABLE [dbo].[TinNhan] CHECK CONSTRAINT [FK_TinNhan_DangNhap]
GO
USE [master]
GO
ALTER DATABASE [CuaHangNoiBo] SET  READ_WRITE 
GO
INSERT INTO DangNhap values(1,'admin',GETDATE(),1)
SELECT * FROM DangNhap
